# Generated by Django 3.1.7 on 2022-05-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpText', models.TextField()),
                ('inpTextLength', models.IntegerField()),
                ('algo1ExtTxt', models.TextField()),
                ('algo1ExtLength', models.IntegerField()),
                ('algo2ExtTxt', models.TextField()),
                ('algo2ExtLength', models.IntegerField()),
                ('algo3AbsTxt', models.TextField()),
                ('algo3AbsLength', models.IntegerField()),
                ('UserChoice', models.IntegerField()),
                ('SentimentScore', models.FloatField()),
            ],
        ),
    ]
